### ISSUE TITLE
The remote certificate is invalid

### ISSUE THREAD

**Issue by JPM-git** [djdd87/SynoAI#148]
First i would like to thank you @djdd87 for the project and efford to improve a greate HW with even better software.

Secound i habe 100% sure this is not an issue on the code but on my setup however i can't find a solution.

The problem seams to be on the fact the Synology native certificate is not recognizes by tge SynoAI framework as a valid certificated.

This is the log, if anyone can help i would appreciate.

info: SynoAI.Startup[0]
      Processing config.
info: SynoAI.Startup[0]
      Processing camera config.
info: SynoAI.Startup[0]
      Processing notifier config.
info: SynoAI.Startup[0]
      Processing Pushbullet Config
info: SynoAI.Startup[0]
      Processing Webhook Config
dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver[1]
      Registered SignalR Protocol: json, implemented by Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.
info: SynoAI.Services.SynologyService[0]
      Initialising
info: SynoAI.Services.SynologyService[0]
      API: Querying end points
fail: SynoAI.Services.SynologyService[0]
      An unhandled exception occurred initialising SynoAI. Exiting...
      System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors
         at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
         at SynoAI.Services.SynologyService.GetEndPointsAsync() in /src/Services/SynologyService.cs:line 62
         at SynoAI.Services.SynologyService.InitialiseAsync() in /src/Services/SynologyService.cs:line 285
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

**Comment by djdd87** [comment]
Have you tried setting AllowInsecureUrl?

**Comment by JPM-git** [comment]
"AllowInsecureUrl": false, --> I know it's the default setting, however even so it still gives the erro.

Even the url i have it on https, if its on http it fails with another error

**Comment by djdd87** [comment]
Have you tried setting it to true though?

**Comment by JPM-git** [comment]
chaging from "AllowInsecureUrl": "false" to "AllowInsecureUrl": "true" did it?!?!

Waht can i say, it's a problem betwwen the chair and the keyboard.

**Comment by JPM-git** [comment]
Thank you.

**Comment by djdd87** [comment]
Setting that to true makes .Net ignore any certificate validation problems, hence why it solves your issue. Happy to help and glad it's working now.
