### ISSUE TITLE
Docker container crashes

### ISSUE THREAD

**Issue by zvirdaniel** [djdd87/SynoAI#184]
Hello. I am using SynoAI inside docker on my Synology DS220+ (using native Docker app) and **in cases of long, continuous movement activity** on my cameras the docker container crashes and get restarted. This happens up to 10 times in one hour.

### Log:

2023-03-19T10:58:42.896109256Z | stdout | Initialising
-- | -- | --
2023-03-19T10:58:42.895965075Z | stdout | [40m[32minfo[39m[22m[49m: SynoAI.Services.SynologyService[0]
2023-03-19T10:58:42.451623070Z | stdout | Processing Pushover Config
2023-03-19T10:58:42.451589055Z | stdout | [40m[32minfo[39m[22m[49m: SynoAI.Startup[0]
2023-03-19T10:58:42.451563164Z | stdout | Processing notifier config.
2023-03-19T10:58:42.451535712Z | stdout | [40m[32minfo[39m[22m[49m: SynoAI.Startup[0]
2023-03-19T10:58:42.451508572Z | stdout | Processing camera config.
2023-03-19T10:58:42.451471742Z | stdout | [40m[32minfo[39m[22m[49m: SynoAI.Startup[0]
2023-03-19T10:58:42.451373303Z | stdout | Processing config.
2023-03-19T10:58:42.351089246Z | stdout | [?1h=[40m[32minfo[39m[22m[49m: SynoAI.Startup[0]
2023-03-19T10:58:15.040833566Z | stdout | at System.Threading.ThreadPoolWorkQueue.Dispatch()
2023-03-19T10:58:15.040788117Z | stdout | at System.Threading.QueueUserWorkItemCallback.Execute()
2023-03-19T10:58:15.040708088Z | stdout | at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
2023-03-19T10:58:15.040674391Z | stdout | at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
2023-03-19T10:58:15.040634037Z | stdout | at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
2023-03-19T10:58:15.040601872Z | stdout | at SynoAI.Controllers.CameraController.Get(String id) in /src/Controllers/CameraController.cs:line 211
2023-03-19T10:58:15.040564115Z | stdout | at SynoAI.Controllers.CameraController.SendNotifications(Camera camera, Notification notification) in /src/Controllers/CameraController.cs:line 447
2023-03-19T10:58:15.040524212Z | stdout | at SynoAI.Notifiers.Pushover.Pushover.SendAsync(Camera camera, Notification notification, ILogger logger) in /src/Notifiers/Pushover/Pushover.cs:line 98
2023-03-19T10:58:15.040420306Z | stdout | at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
2023-03-19T10:58:15.020266223Z | stdout | at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023-03-19T10:58:15.020235901Z | stdout | at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023-03-19T10:58:15.020192046Z | stdout | at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2023-03-19T10:58:15.020161709Z | stdout | at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023-03-19T10:58:15.020130853Z | stdout | at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023-03-19T10:58:15.020045786Z | stdout | at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
2023-03-19T10:58:15.020002372Z | stdout | at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync\|56_0(ValueTask copyTask)
2023-03-19T10:58:15.019912765Z | stdout | at System.Net.Http.MultipartContent.SerializeToStreamAsyncCore(Stream stream, TransportContext context, CancellationToken cancellationToken)
2023-03-19T10:58:15.019884441Z | stdout | at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync\|56_0(ValueTask copyTask)
2023-03-19T10:58:15.019854881Z | stdout | --- End of inner exception stack trace ---
2023-03-19T10:58:15.019802769Z | stdout | at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync\|56_0(ValueTask copyTask)
2023-03-19T10:58:15.019767990Z | stdout | at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
2023-03-19T10:58:15.019732124Z | stdout | at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source, Boolean async)
2023-03-19T10:58:15.019687804Z | stdout | at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
2023-03-19T10:58:15.019639627Z | stdout | at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
2023-03-19T10:58:15.019599008Z | stdout | at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteWriteAsync\|177_1[TIOAdapter](ValueTask writeTask, Byte[] bufferToReturn)
2023-03-19T10:58:15.019536757Z | stdout | at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2023-03-19T10:58:15.019457396Z | stdout | at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2023-03-19T10:58:15.019424497Z | stdout | --- End of inner exception stack trace ---
2023-03-19T10:58:15.019388916Z | stdout | ---> System.Net.Sockets.SocketException (32): Broken pipe
2023-03-19T10:58:15.019335098Z | stdout | ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
2023-03-19T10:58:15.018928149Z | stdout | Unhandled exception. System.Net.Http.HttpRequestException: Error while copying content to a stream.

**Comment by djdd87** [comment]
Does this occur if you use another service? e.g. Pushbullet/Telegram/etc? Just hypothesising based on the error "Unable to write data to the transport connection: Broken pipe.", which implies it's being disconnected from the other party: it could be a rate limiting feature on Pushover. I don't use it myself, so I've not come across this problem.

**Comment by DerPicknicker** [comment]
I get a similar output in my log. I use pushover with paid apps. But I guess it's not caused by Pushover because, if a lot of People are in front of the Camera I get always the Notifications. But from time to time I got this log too: 
```
Unhandled exception. System.Net.Http.HttpRequestException: Error while copying content to a stream.
stdout
15:06:08
 ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
stdout
15:06:08
 ---> System.Net.Sockets.SocketException (32): Broken pipe
stdout
15:06:08
   --- End of inner exception stack trace ---
stdout
15:06:08
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
stdout
15:06:08
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
stdout
15:06:08
   at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteWriteAsync|177_1[TIOAdapter](ValueTask writeTask, Byte[] bufferToReturn)
stdout
15:06:08
   at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
stdout
15:06:08
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
stdout
15:06:08
   at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source, Boolean async)
stdout
15:06:08
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
stdout
15:06:08
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
stdout
15:06:08
   --- End of inner exception stack trace ---
stdout
15:06:08
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
stdout
15:06:08
   at System.Net.Http.MultipartContent.SerializeToStreamAsyncCore(Stream stream, TransportContext context, CancellationToken cancellationToken)
stdout
15:06:08
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
stdout
15:06:08
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
stdout
15:06:08
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
stdout
15:06:08
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
stdout
15:06:08
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
stdout
15:06:08
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
stdout
15:06:08
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
stdout
15:06:08
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
stdout
15:06:08
   at SynoAI.Notifiers.Pushover.Pushover.SendAsync(Camera camera, Notification notification, ILogger logger) in /src/Notifiers/Pushover/Pushover.cs:line 98
stdout
15:06:08
   at SynoAI.Controllers.CameraController.SendNotifications(Camera camera, Notification notification) in /src/Controllers/CameraController.cs:line 405
stdout
15:06:08
   at SynoAI.Controllers.CameraController.Get(String id) in /src/Controllers/CameraController.cs:line 191
stdout
15:06:08
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
stdout
15:06:08
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
stdout
15:06:08
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
stdout
15:06:08
   at System.Threading.QueueUserWorkItemCallback.Execute()
stdout
15:06:08
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
stdout
15:06:34
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
stdout
15:06:34
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
```
