### ISSUE TITLE
The configured user limit (128) on the number of inotify instances has been reached

### ISSUE THREAD

**Issue by cedlap** [djdd87/SynoAI#196]
I've been having this crash on startup for a while. Container shuts down immediately. Not sure what's going on. It's running on unRAID, I have a lot of inotify available on the host.

```
docker run
  -d
  --name='SynoAI'
  --net='bridge'
  -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="unRAID"
  -e HOST_CONTAINERNAME="SynoAI"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='000'
  -e 'TZ'='Europe/Brussels'
  -l net.unraid.docker.managed=dockerman
  -p '8134:80/tcp'
  -v '/mnt/user/appdata/SynoAI/appsettings.json':'/app/appsettings.json':'rw'
  -v '/mnt/user/appdata/SynoAI/Captures':'/app/Captures':'rw' 'djdd87/synoai:latest'
```

```
Unhandled exception. System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at SynoAI.Program.Main(String[] args) in /src/Program.cs:line 11
```

**Comment by cedlap** [comment]
Yeah. Adding fs.inotify.max_user_instances=2048 to /etc/sysctl.conf on the host fixed it for now. 
But yes I think it's something that could be avoided. Perhaps using an alpine image?
Thanks!
