### ISSUE TITLE
Unable to start docker after HA cluster failover

### ISSUE THREAD

**Issue by mileyceberus** [djdd87/SynoAI#43]
SynoAI docker is currently installed on DSM 7 cluster with 2 members (A & B).

Unfortunately, SynoAI can only start up on **_member A_** of the cluster. Deepstack, however, can be started on **any** active member of the HA cluster.

Whenever SynoAI is started on **_member B_** (after the failover), Docker becomes unresponsive. SynoAI continuously fails with the following error code **_resource temporarily unavailable_**.

```
2021-08-06T14:16:46+10:00 dsm synoscgi_SYNO.Docker.Container_1_get[29947]: api_helper.cpp:238 Fail to receive data. Return value of recv: -1, Resource temporarily unavailable
2021-08-06T14:16:46+10:00 dsm synoscgi_SYNO.Docker.Container_1_get[29947]: container.cpp:1329 Fail to inspect container [djdd87-synoai]. statusCode: [500], _errMsg: [null]
2021-08-06T14:16:46+10:00 dsm synoscgi_SYNO.Docker.Container_1_get[29947]: container.cpp:2141 Failed to call cInspect()
2021-08-06T14:16:46+10:00 dsm synoscgi[7885]: socket_process_manager.cpp:726 child 29947 exited with signal 13
2021-08-06T14:16:46+10:00 dsm synoscgi_SYNO.Docker.Container_1_get_process[29946]: api_helper.cpp:238 Fail to receive data. Return value of recv: -1, Resource temporarily unavailable

```

The extended logging information did not reveal much useful information - apart from saying that the surveillance station was not accessible (not true as I could manually login to surveillance station using the details in appsettings.json).

```
2021-08-06 04:41:46,stdout,crit: Microsoft.AspNetCore.Server.Kestrel[0]
2021-08-06 04:41:46,stdout,fail: SynoAI.Services.SynologyService[0]
2021-08-06 04:41:46,stdout,         --- End of inner exception stack trace ---
2021-08-06 04:41:46,stdout,         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
2021-08-06 04:41:46,stdout,         at SynoAI.Services.SynologyService.GetEndPointsAsync() in /src/Services/SynologyService.cs:line 64
2021-08-06 04:41:46,stdout,         at SynoAI.Services.SynologyService.InitialiseAsync() in /src/Services/SynologyService.cs:line 276
2021-08-06 04:41:46,stdout,         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2021-08-06 04:41:46,stdout,       ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
2021-08-06 04:41:46,stdout,      An unhandled exception occurred initialising SynoAI. Exiting...
2021-08-06 04:41:46,stdout,      Application is shutting down...
2021-08-06 04:41:46,stdout,      System.Net.Http.HttpRequestException: Resource temporarily unavailable (dsm.home.xxx.com:5001)
2021-08-06 04:41:46,stdout,      System.Threading.Tasks.TaskCanceledException: A task was canceled.
2021-08-06 04:41:46,stdout,      Unable to start Kestrel.
2021-08-06 04:41:46,stdout,   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
2021-08-06 04:41:46,stdout,   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
2021-08-06 04:41:46,stdout,   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2021-08-06 04:41:46,stdout,   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
```

No configuration changes occur during the HA failover. Directories and configurations are fully sync-ed across both cluster members.

Please advise if any other parameters can be enabled to troubleshoot the issue. Logging is currently set to "Information" on appsettings.json.

**Comment by mileyceberus** [comment]
Container had incorrect dns host.
