### ISSUE TITLE
SynoAI docker container keeps crashing after "Querying end points"

### ISSUE THREAD

**Issue by tim661811** [djdd87/SynoAI#45]
The following logs are outputted by the docker container:
```
info: SynoAI.Startup[0]
      Processing config.
info: SynoAI.Startup[0]
      Processing camera config.
info: SynoAI.Startup[0]
      Processing notifier config.
info: SynoAI.Startup[0]
      Processing Telegram Config
info: SynoAI.Services.SynologyService[0]
      Initialising
info: SynoAI.Services.SynologyService[0]
      API: Querying end points
fail: SynoAI.Services.SynologyService[0]
      An unhandled exception occurred initialising SynoAI. Exiting...
      System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
       ---> System.TimeoutException: The operation was canceled.
       ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
         at SynoAI.Services.SynologyService.GetEndPointsAsync() in /src/Services/SynologyService.cs:line 64
         at SynoAI.Services.SynologyService.InitialiseAsync() in /src/Services/SynologyService.cs:line 276
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at SynoAI.Program.Main(String[] args) in /src/Program.cs:line 16
```
   
I'm using the following Config:
```
{
	"Logging": {
		"LogLevel": {
			"Default": "Information",
			"Microsoft": "Warning",
			"Microsoft.Hosting.Lifetime": "Information"
		}
	},
	"Url": "http://192.168.0.10:5000",
	"User": "admin",
	"Password": "SuperSecretPassword",
	"MinSizeX": 100,
	"MinSizeY": 100,
	"AI": {
		"Type": "DeepStack",
		"Url": "http://192.168.0.10:83"
	},
	"Notifiers": [
		{
			"Type": "Telegram",
			"ChatID": "SuperSecretChatID",
			"Token": "SuperSecretToken",
			"PhotoBaseURL": ""
		}
	],
	"Cameras": [
		{
			"Name": "FI9900P_FRONT",
			"Types": [ "Person" ],
			"Threshold": 45
		},
		{
			"Name": "IPC-G26E_BACK",
			"Types": [ "Person", "Cat" ],
			"Threshold": 30
		}
	]
}
```

The Deepstack AI container is displaying the page with the "DeepStack Activated" message on port 83.
Running the code on a PC via the cloned repo does work.

**Comment by djdd87** [comment]
Hi this is an issue with your firewall/network settings. See #44.

**Comment by tim661811** [comment]
I still dont fully understand why its a firewall issue and how i fix it but when using your WAN ip or ddns url for the DSM link it works fine

**Comment by djdd87** [comment]
The timeout is because it gets no response. Unfortunately it's not a SynoAI issue and will be a docker network configuration issue or a firewall issue (as shown by the fact you said it works fine when run using the code).
