### ISSUE TITLE
SynoAI crashing when ShowExclusions: true for cameras with no exclusions

### ISSUE THREAD

**Issue by p-u-a** [djdd87/SynoAI#77]
I think this is what's happening.  I have one camera with an exclusion zone that is working well, and draws the exclusion zone correctly.  However with "ShowExclusions": true, any camera that has no exclusion zone is crashing the container.  I could see this happening by setting it to true, then manually triggering a camera with and without an exclusion zone.  The camera with would work fine, but the one without would crash every time, until I set it false.  I got this from the log, hope it helps...

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SynoAI.Services.SnapshotManager.DressImage(Camera camera, Byte[] snapshot, IEnumerable`1 predictions, IEnumerable`1 validPredictions, ILogger logger) in /src/Services/SnapshotManager.cs:line 36
   at SynoAI.Controllers.CameraController.Get(String id) in /src/Controllers/CameraController.cs:line 190
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by djdd87** [comment]
Yep you're right. Thanks for the repro. I'll put a fix out later.

**Comment by p-u-a** [comment]
No worries, and thanks again for such an awesome app.

**Comment by djdd87** [comment]
Fixed and now available in the :latest image. I'll do a proper 1.0.1 bug fix release later.

**Comment by p-u-a** [comment]
Awesome, thanks so much, this is still such a great addon to SSS.
